<?php
return [
    
'PLATAFORMA_PATH'=>env('PLATAFORMA_PATH' ),
'TILESERVER_PATH'=>env('TILESERVER_PATH' ),
'TILESERVER_STYLE_FILE'=> env('TILESERVER_STYLE_FILE'),
'TILES_SERVER_URL'=>env('TILES_SERVER_URL' ),
'TILESERVER_STORAGE_PATH'=>env('TILESERVER_STORAGE_PATH' ),
];

 